version: '2'
services:
  mongo:
    image: mongo
    restart: always
  
  robot:  
    container_name: "mancala-game"
    restart: always
    image: code/mancala-game:latest
    volumes:
        - .:/var/www:rw
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
    ports:
        - 8080:8080